### ISSUE TITLE
Crash when browsing a site hosted in Pretzel taste

### ISSUE THREAD

**Issue by tathamoddie** [Code52/pretzel#102]
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message="An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
  Source=System
  StackTrace:
       at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
       at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
       at Firefly.Utils.SocketWrapper.ReceiveAsync(SocketAsyncEventArgs e) in :line 0
       at Firefly.Http.Connection.Go(Boolean newFrame) in :line 0
       at Firefly.Http.Connection.<ProduceEnd>b__13(Object _) in :line 0
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  InnerException:

**Comment by laedit** [comment]
Fixed by #298.
