### ISSUE TITLE
Exception while navigating between pages during tasting

### ISSUE THREAD

**Issue by harouny** [Code52/pretzel#164]
I got this happening a couple of times while moving from one page to another. Not sure about the exact scenario though. I'm using Windows Server 2008 R2 Standard

>System.ObjectDisposedException was unhandled
  HResult=-2146232798
  Message=Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
  Source=System
  ObjectName=System.Net.Sockets.Socket
  StackTrace:
       at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
       at Firefly.Utils.SocketWrapper.Shutdown(SocketShutdown how)
       at Firefly.Http.Connection.<>c__DisplayClass9.<ProduceEnd>b__4()
       at Firefly.Utils.SocketSender.<>c__DisplayClass6.<DoFlush>b__3()
       at Firefly.Utils.SocketSender.SetStateImmediate()
       at Firefly.Utils.SocketSender.DoSendCompleted()
       at Firefly.Utils.SocketSender.SocketEventCompleted()
       at Firefly.Utils.SocketEventWrapper.SocketEventCompleted(Object sender, SocketAsyncEventArgs e)
       at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
       at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
       at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
       at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
  InnerException:

**Comment by markvantilburg** [comment]
See #147

**Comment by markvantilburg** [comment]
@laedit this one can be closed.
