### ISSUE TITLE
`NullReferenceException` in ScriptCs

### ISSUE THREAD

**Issue by thoemmi** [Code52/pretzel#278]
I already mentioned this in #275, but my assumptions were wrong. Therefore this new issue.

The `NullReferenceException` happens in `ScriptCsCatalogFactory.CreateScriptCsCatalog`, i.e. before the script is even executed:
![image](https://cloud.githubusercontent.com/assets/73690/11314691/1d5e0890-8fe8-11e5-81fe-92e6fa7d0f9c.png)

The stacktrace is:
```
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.InitializerDimensions(BoundArrayInitialization init)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAllElementInitializers(ArrayTypeSymbol arrayType, BoundArrayInitialization inits, Boolean skipConstants)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitVectorInitializers(ArrayTypeSymbol arrayType, BoundArrayInitialization inits)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArrayCreationExpression(BoundArrayCreation expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArguments(ReadOnlyArray`1 arguments, ReadOnlyArray`1 parameters)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitObjectCreationExpression(BoundObjectCreationExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAssignmentValue(BoundAssignmentOperator assignmentOperator)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAssignmentExpression(BoundAssignmentOperator assignmentOperator, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitBlockStatement(BoundBlock block)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitSequencePointWithSpan(BoundSequencePointWithSpan node)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Generate()
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Run(MethodSymbol meth, BoundStatement block, ILBuilder builder, Module module, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints)
   at Roslyn.Compilers.CSharp.Compiler.GenerateMethodBody(TypeCompilationState compilationState, MethodSymbol method, BoundStatement block, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints, Func`2 mapFileNameToDebugDoc, ReadOnlyArray`1 namespaceScopes)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileMethod(MethodSymbol methodSymbol, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileNamedType(NamedTypeSymbol symbol)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.<>c__DisplayClass6.<VisitNamedType>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.WaitForWorkers()
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation compilation, DiagnosticBag diagnostics, Type delegateType, Boolean collectible, CancellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.CompileSubmission[T](String code, Session session, String path, Boolean isInteractive)
   at ScriptCs.Engine.Roslyn.RoslynScriptEngine.Execute(String code, Session session)
--- End of stack trace from previous location where exception was thrown ---
   at ScriptCs.ComponentModel.Composition.ScriptCsCatalog.ExecuteScripts(IEnumerable`1 scriptFiles)
   at ScriptCs.ComponentModel.Composition.ScriptCsCatalog.Initialize(String path, String searchPattern, ScriptCsCatalogOptions options)
   at ScriptCs.ComponentModel.Composition.ScriptCsCatalog..ctor(String path, String searchPattern, ScriptCsCatalogOptions options)
   at ScriptCs.ComponentModel.Composition.ScriptCsCatalog..ctor(String path, ScriptCsCatalogOptions options)
   at Pretzel.ScriptCs.ScriptCsCatalogFactory.CreateScriptCsCatalog(String pluginsFolderPath, Type[] references) in D:\Documents\GitHub\pretzel\src\Pretzel.ScriptCs\ScriptCsPluginsEngine.cs:line 11
```

Here's the script `test.csx` (I took [my code](https://github.com/thoemmi/Pretzel.Sitemap/blob/master/Pretzel.Sitemap/SitemapTransform.cs) from Pretzel.Sitemap and reduced it to the smallest snippet that produces the error.)
```csharp
public class DemoTransform : ITransform {
    private static readonly XNamespace _xmlns = "http://www.sitemaps.org/schemas/sitemap/0.9";
    private static readonly XNamespace _xsi = "http://www.w3.org/2001/XMLSchema-instance";
	
    private readonly IFileSystem _fileSystem;
	
    [ImportingConstructor]
	public DemoTransform(IFileSystem fileSystem) {
		_fileSystem = fileSystem;
    }

    public void Transform(SiteContext siteContext) {
		var siteUrl = siteContext.Config["url"];

		 var urlsetElement = new XElement(_xmlns + "urlset",
		 	new XAttribute("xmlns", _xmlns),
		 	new XAttribute(XNamespace.Xmlns + "xsi", _xsi),
		 	new XAttribute(_xsi + "schemaLocation", "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"));
	}
}
```

**Comment by laedit** [comment]
I had to add 
``` C#
#r  System.Xml.Linq.dll

using System.Xml.Linq;
```
To make it work but I was able to reproduce it.

The good news is it seems that Pretzel isn't the source of the problem.
The bad news is it seems that Roslyn is...

I'll have to test if the last version of ScriptCs is good and update ScriptCs.ComponentModel.Composition and Pretzel.ScriptCs if necessary, this will take some time.

**Comment by thoemmi** [comment]
I had a look at the ScriptCs issues, https://github.com/scriptcs/scriptcs/issues/1095 looks exactly like my stacktrace. I could verify that Pretzel works with Platform changed to x64 (is there a reason Pretzel is x86 instead of AnyCPU?)

According to https://github.com/scriptcs/scriptcs/pull/1064 it should be fixed with the next release v0.16.

**Comment by laedit** [comment]
Thanks, I haven't got the time to look at it today.
I don't think there is a specific reason, could you try?

**Comment by thoemmi** [comment]
As I said, I changed Platform target of Pretzel to x64. With that setting Pretzel works perfectly, i.e. the exception does not occur.

**Comment by thoemmi** [comment]
BTW, I asked ScriptCs's [Jabbr room](https://jabbr.net/#/rooms/scriptcs) for an ETA of v0.16.

**Comment by laedit** [comment]
Thanks, I'll update ScriptCs when it will be released.
In the meantime I have aligned all projects to "Any CPU" to fix the issue.

**Comment by thoemmi** [comment]
Thanks @laedit. There are still configurations for x86 in the Pretzel project. Wouldn't it be more convenient to remove those and only keep AnyCPU?

**Comment by laedit** [comment]
You're right, it is done.

**Comment by thoemmi** [comment]
I just got to know that there is a feed for nightly builds of ScriptCS, https://myget.org/gallery/scriptcsnightly. What do you think of using these instead of waiting for the next release?

**Comment by laedit** [comment]
It is possible, but only for master branch. I'm not comfortable to release a version based on a nightly.

**Comment by thoemmi** [comment]
Well, I think I gonna rewrite my plugins to compiled assemblies until this issue is fixed :unamused:

**Comment by laedit** [comment]
Sorry
