### ISSUE TITLE
Deleting images causes crash

### ISSUE THREAD

**Issue by JakeGinnivan** [Code52/pretzel#92]
Will investigate later, just reporting for now

File change: C:\Users\Jake\_Code\Documentation\img

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Us
ers\Jake\_Code\Documentation\img\2Controllers2.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at System.IO.Abstractions.FileInfoWrapper.CopyTo(String destFileName, Boolean
 overwrite) in :line 0
   at Pretzel.Logic.Templating.Context.SiteContextGenerator.SafeReadLine(String
file) in c:\Users\Jake\_Code\pretzel\src\Pretzel.Logic\Templating\Context\SiteCo
ntextGenerator.cs:line 249
   at Pretzel.Logic.Templating.Context.SiteContextGenerator.ContainsYamlFrontMat
ter(String file) in c:\Users\Jake\_Code\pretzel\src\Pretzel.Logic\Templating\Con
text\SiteContextGenerator.cs:line 146
   at Pretzel.Logic.Templating.Context.SiteContextGenerator.<BuildPages>d__c.Mov
eNext() in c:\Users\Jake\_Code\pretzel\src\Pretzel.Logic\Templating\Context\Site
ContextGenerator.cs:line 76
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Pretzel.Logic.Templating.Context.SiteContextGenerator.BuildContext(String
path) in c:\Users\Jake\_Code\pretzel\src\Pretzel.Logic\Templating\Context\SiteCo
ntextGenerator.cs:line 57
   at Pretzel.Commands.TasteCommand.WatcherOnChanged(String file) in c:\Users\Ja
ke\_Code\pretzel\src\Pretzel\Commands\TasteCommand.cs:line 88
   at Pretzel.Modules.SimpleFileSystemWatcher.WatcherOnChanged(Object sender, Fi
leSystemEventArgs args) in c:\Users\Jake\_Code\pretzel\src\Pretzel\Modules\Simpl
eFileSystemWatcher.cs:line 42
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String
 name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt
32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by markvantilburg** [comment]
I cannot get it to crash with the current version.

Tried flow:
```
Run site with 'taste'
Delete main logo of the website
Refresh site
Restore main logo of the website
Refresh site
```

This might be fixed in the most recent builds.

**Comment by laedit** [comment]
Thanks @markvantilburg for your help! 😃 
You are right, Pretzel no longer try to copy deleted files.
